### ISSUE TITLE
Configuration of voice

### ISSUE THREAD

**Issue by boveyking** [lspahija/AIUI#12]
Suggest to expose a config setting to let user choose which voice to use. like premade vocie (Elli/Adam/Bella) in ElevanLabs.

The voice in author's demo works perfectly, however, when I deployed to my server, the voice is not nature and smooth. It speeks like robot.

Is a quick way to config which voice to use?

**Comment by lspahija** [comment]
done: https://github.com/lspahija/AIUI/commit/99ddeff9d7981d576e9869aba914b0ba417c0600
