### ISSUE TITLE
offer a totally a free  edge-tts  Text to Speech

### ISSUE THREAD

**Issue by joe12801** [lspahija/AIUI#16]
offer  a totally a free  edge-tts  Text to Speech

coz edge tts include more a voice to choose

it is free. see this project , can add those voice in your project must be very perfect 

https://github.com/rany2/edge-tts

**Comment by joe12801** [comment]
coz edge tts include more  100  voices  to choose

**Comment by joe12801** [comment]
Use Microsoft Edge's online text-to-speech service from Python (without needing Microsoft Edge/Windows or an API key)

**Comment by lspahija** [comment]
done: https://github.com/lspahija/AIUI/blob/main/app/tts.py#L33-L43

**Comment by joe12801** [comment]
> done: https://github.com/lspahija/AIUI/blob/main/app/tts.py#L33-L43

thanks you .good job bro
