### ISSUE TITLE
hi  big man,  one cilck  deploy  on Railway  is  on road  map?

### ISSUE THREAD

**Issue by yangyayuan** [lspahija/AIUI#17]
this  project  its  amazing  .

**Comment by lspahija** [comment]
done: https://github.com/lspahija/AIUI/commit/dc2c1d117a6e04d53d542116ddfb1945ea0a279a

Thanks for the kind words!

**Comment by yangyayuan** [comment]
so  so  so  fast   just 30 minutes have passed
