### ISSUE TITLE
AI speaking always was reset

### ISSUE THREAD

**Issue by boveyking** [lspahija/AIUI#22]
After deployed to railway.app, the app got reset every time when AI speaking started. 
Checked the logs from railway, the user prompt was successfully transcripted; response from ChatGPT was complete; the returned text from chatGPT was sucessfully posted to elevenlabs; and the audio was also correctly generated by elevenlabs(I can see the text and playback the audio from elevenlabs history).

however, when audio returned from elevenlabs, AI started to beep and stoped(I checked in browser console, a reset was immediately fired after ai speaking started).

pls check the issue here:
https://speechtopia.up.railway.app/index.html

the configuration and apikey are all correct.
what is the reason for the reset? thanks.

**Comment by lspahija** [comment]
fixed here: https://github.com/lspahija/AIUI/commit/aeae22a0cd73e68892fb3696fc57db4ab21680aa

please redeploy with the latest code

**Comment by boveyking** [comment]
Still same issue after redeployed.

**Comment by lspahija** [comment]
Did you set the `OPENAI_API_KEY` and `ELEVENLABS_API_KEY` environment variables? What is being logged in the Deploy Logs in Railway?

**Comment by boveyking** [comment]
OPENAI_API_KEY and ELEVENLABS_API_KEY are all set.

However, this happened for edge_tts too.

**Comment by lspahija** [comment]
I will need to see your logs to understand what is happening.
