### ISSUE TITLE
Git clone says "don't have permission"

### ISSUE THREAD

**Issue by lightningquick** [lspahija/AIUI#35]
Works if we use the link from <code> button

Here is the exact message 

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by boveyking** [comment]
Are  you  using VPN or behind proxy?

**Comment by bragabruno** [comment]
we should use git clone https://github.com/lspahija/AIUI.git instead of git clone git@github.com:lspahija/AIUI.git.

**Comment by lspahija** [comment]
To clone GitHub repos using the SSH protocol, you have to add your SSH key to your GitHub account:
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
