### ISSUE TITLE
Respond as per asked language

### ISSUE THREAD

**Issue by Sblop** [lspahija/AIUI#4]
Suggestion:
When I use VoxGPT in English everything works perfectly. If I change the language to Danish, clearly a danish language model is used, however chatGPT response is often in English, not Danish. Sponken by a danish voice, meaning garbled english. For this reason I must ask the bot to: (translated from danish) "Please explain in Danish, how a ..." or similar. I must declare I want my answer in Danish. Perhaps the api request sent to openai, should include: "Answer question in XXXXX (language) only: question blah blah...."
Does this make sense? I am aware that the promt in the script writes "respond in the same language as was spoken" however for me I have problems. Several replies in English. Sometimes in Swedish and Norwegian (these are close to danish). This would however be solved by stating this directly in the promt.

**Comment by lspahija** [comment]
Added in this commit: https://github.com/lspahija/VoxGPT/commit/8cca03987db2cccd6f993322f4b7a232e5e85aa6
